version: '3'

services:

  backend:
    build: ./
    restart: always
    command: python /app/src/main.py
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - ngrok

  ngrok:
    build:
      context: ./ngrok
      args:
        - NGROK_AUTHTOKEN=$NGROK_AUTHTOKEN
    restart: always
    command: sh -c "/bin/ngrok config upgrade \
             && /bin/ngrok http --config /root/.config/ngrok/ngrok.yml backend:${FLASK_PORT} \
             | tee /var/log/ngrok.log"
    volumes:
      - ./logs:/var/log
    env_file:
      - .env
