name: Hello From GitHub Actions


on:
  push:
    branches:
      - ref3


jobs:

  Say-Hello:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

#        - uses: actions/checkout@v2
#
#        - name: Hello World
#          run: echo "Hello World"
