name: Run Test

on:
  push:
    branches:
      - Refactoring

jobs:

  test_all:
    runs-on: ubuntu-latest

    steps:
      - name: Hello from test
        run: echo "Hello from test"

      - name: Checkout latest code
        run: actions/checkout@v2

#      - name: Run lint
#        run: npm run lint
#
#      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
